# Generated by Django 3.2.12 on 2022-10-29 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSBaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('rssbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rss.rssbasemodel')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
            },
            bases=('rss.rssbasemodel',),
        ),
        migrations.CreateModel(
            name='RSSFeedActivity',
            fields=[
                ('rssbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rss.rssbasemodel')),
                ('is_followed', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.rssfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSS Feed Activity',
                'verbose_name_plural': 'RSS Feed Activities',
            },
            bases=('rss.rssbasemodel',),
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('rssbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rss.rssbasemodel')),
                ('item', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('base', models.CharField(blank=True, max_length=512, null=True)),
                ('summary', models.CharField(blank=True, max_length=1024, null=True)),
                ('published', models.CharField(blank=True, max_length=128, null=True)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.rssfeed')),
            ],
            options={
                'verbose_name': 'Feed Item',
                'verbose_name_plural': 'Feed Items',
            },
            bases=('rss.rssbasemodel',),
        ),
        migrations.CreateModel(
            name='FeedItemActivity',
            fields=[
                ('rssbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rss.rssbasemodel')),
                ('is_read', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.feeditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feed Item Activity',
                'verbose_name_plural': 'Feed Item Activities',
                'unique_together': {('user', 'item')},
            },
            bases=('rss.rssbasemodel',),
        ),
    ]
